# Generated by Django 4.2 on 2023-05-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostView',
            new_name='PostVisit',
        ),
    ]
