# Generated by Django 4.2 on 2023-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_postvisit_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('browser_family', models.CharField(max_length=50)),
                ('os_family', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='postvisit',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
