# Generated by Django 4.2 on 2023-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='accent',
            field=models.CharField(blank=True, default='#0073ff', max_length=20),
        ),
    ]
