# Generated by Django 4.2 on 2023-05-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='profile_pic',
        ),
    ]
