# Generated by Django 4.2 on 2023-05-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_authorprofile_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
    ]
