# Generated by Django 4.2 on 2023-05-19 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following_authors',
        ),
        migrations.AddField(
            model_name='user',
            name='following_authors',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
